version: '3'
services:
  toko:
    build:
      context: .
    volumes:
      - ./:/api
    command: yarn start:dev
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  db:
    image: mariadb:10.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - /var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: nestday7
