version: '2'
services:
  db_data:
    image: busybox
    volumes:
      - ./db:/var/lib/mysql
  db:
    image: mariadb:10.5
    build: ./db/
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes_from:
      - db_data
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: nestday7
      MYSQL_ROOT_PASSWORD: password
