name: Publish Docker image
on:
  push:
    # タグをpushしたら実行されるように
    tags:
      - 'v*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/ruritoblogger/toko
      -
        # GitHub Container Registry にログインする
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}      # secretで作成したものを指定
      -
        # イメージビルドしてGitHub Container Registry に pushする
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}